version: "3"
services:
  devicesim1:
    image: onosproject/device-simulator:latest
    environment:
      - HOSTNAME=localhost
      - GNMI_PORT=10161
      - GNMI_INSECURE_PORT=11161
      - SIM_MODE=1
    ports:
      - "10161:10161"
      - "11161:11161"
    labels:
      description: "gNMI Simulator Device 1"
  devicesim2:
    image: onosproject/device-simulator:latest
    environment:
      - HOSTNAME=localhost
      - GNMI_PORT=10162
      - GNMI_INSECURE_PORT=11162
      - SIM_MODE=1
    ports:
      - "10162:10162"
      - "11162:11162"
    labels:
      description: "gNMI Simulator Device 2"
  devicesim3:
    image: onosproject/device-simulator:latest
    environment:
      - HOSTNAME=localhost
      - GNMI_PORT=10163
      - GNMI_INSECURE_PORT=11163
      - SIM_MODE=1
    ports:
      - "10163:10163"
      - "11163:11163"
    labels:
      description: "gNMI Simulator Device 3"
