version: "3"
services:
  devicesim1:
    image: onosproject/device-simulator:latest
    environment:
      - HOSTNAME=localhost
      - GNOI_PORT=50001
      - GNMI_PORT=10161
      - GNMI_INSECURE_PORT=11161
      - SIM_MODE=3
    ports:
      - "50001:50001"
      - "10161:10161"
      - "11161:11161"
    labels:
      description: "gNOI/gNMI Simulator Device 1"  
  devicesim2:
    image: onosproject/device-simulator:latest
    environment:
      - HOSTNAME=localhost
      - GNOI_PORT=50002
      - GNMI_PORT=10162
      - GNMI_INSECURE_PORT=11162
      - SIM_MODE=3  
    ports:
      - "50002:50002"
      - "10162:10162"
      - "11162:11162"
    labels:
      description: "gNOI/gNMI Simulator Device 2"
  devicesim3:
    image: onosproject/device-simulator:latest
    environment:
      - HOSTNAME=localhost
      - GNOI_PORT=50003
      - GNMI_PORT=10163
      - GNMI_INSECURE_PORT=11163
      - SIM_MODE=3  
    ports:
      - "50003:50003"
      - "10163:10163"
      - "11163:11163"
    labels:
      description: "gNOI/gNMI Simulator Device 3"               
